# Generated by Django 3.2.9 on 2021-11-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
