# Generated by Django 3.2.9 on 2021-11-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='link',
            field=models.CharField(blank=True, default='#', max_length=200),
        ),
    ]
